### ISSUE TITLE
Example Profiling Data

### ISSUE THREAD

**Issue by gwaybio** [cytodata/awesome-cytodata#3]
From what I can tell, the three entries (BBBC, IDR, RxRx1) in the datasets resource section include only raw images.

Are there any known examples of resources that provide actual profiles (in addition to raw images)?

One of the major reasons for success in RNA space is that processed matrices are made available alongside raw data. This enables really quick secondary analyses. I haven't really seen much of this for profiling data.

**Comment by gwaybio** [comment]
It looks like [Wawer et al. 2014](https://www.pnas.org/content/111/30/10911.long) provides processed profiles. Maybe it is more common than I thought!

**Comment by gwaybio** [comment]
some processed profiles here: https://github.com/cytodata/cytodata-hackathon-2018#data-available-on-aws

**Comment by gwaybio** [comment]
here are some more publicly available profiles:

https://docs.google.com/spreadsheets/d/1iNzLmISGxXmDlmZk_Edw5Pp4WBp3pUsmcp8iR7NUFv4/edit#gid=1262001141

I will add to the list soon!

**Comment by AnneCarpenter** [comment]
I believe all papers published by our lab provided the processed profiles in some fashion, either as supplementary data or in the github repo for the paper (in carpenterlab umbrella).

**Comment by gwaybio** [comment]
Great! I feel like I captured them all in #4 _except_ for https://github.com/carpenterlab/2016_bray_natprot. I will add this in the next PR!
